version: "2.1"

services:
  mc_pg:
    image: postgres

  mc_base:
    build:
      context: ./
      dockerfile: mc.Dockerfile
      args:
        MINICONDA_URL: ${MINICONDA_URL-https://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh}
    environment:
      DJANGO_SETTINGS_MODULE: 'mc_dj.settings'
      MC_DB_NAME: postgres
      MC_DB_USER: postgres
      MC_DB_PASSWORD: postgres
      MC_DB_HOST: mc_pg
      MINICONDA_URL: ${MINICONDA_URL-https://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh}

  mc_server:
    extends:
      service: mc_base
    command: cd /mc && python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./mc:/mc
    depends_on:
      - mc_pg

  mc_shell:
    extends:
      service: mc_base
    command: /bin/bash
    volumes:
      - ./:/mc_root
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "MC_ROOT=$PWD"
      - "PYTHONPATH=/mc_root"
    depends_on:
      - mc_pg
    privileged: true

networks:
  default:
    driver: bridge
    labels:
      - "mc.network=mc"
