version: "2"
services:
  mc_pg:
    image: postgres
  mc_base:
    build:
      context: ./
      dockerfile: mc.Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: 'mc.settings'
      FW_CONFIG_FILE: '/mc/fireworks/FW_config.yaml'
      MC_DB_NAME: postgres
      MC_DB_USER: postgres
      MC_DB_PASSWORD: postgres
      MC_DB_HOST: mc_pg
  mc_server:
    extends:
      service: mc_base
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./mc:/mc
    depends_on:
      - mc_pg
  mc_shell:
    extends:
      service: mc_base
    command: /bin/bash
    volumes:
      - ./mc:/mc
    depends_on:
      - mc_pg
      - mc_server
